### ISSUE TITLE
rawGetter is not a function

### ISSUE THREAD

**Issue by CafaAsbl** [pagekit/vue-resource#534]
Hi everyone,

I got an error that i don't understand where it came from. 
It say : 

> TypeError: rawGetter is not a function
> at wrappedGetter (eval at <anonymous> (http://localhost:3000/app.js:654:2), <anonymous>:703:12)
> at Vue$3.computed.(anonymous function) (eval at <anonymous> (http://localhost:3000/app.js:654:2), <anonymous>:517:42)
>at Watcher.get (eval at <anonymous> (http://localhost:3000/app.js:600:2), <anonymous>:1661:27)
> at Watcher.evaluate (eval at <anonymous> (http://localhost:3000/app.js:600:2), <anonymous>:1769:21)
>at Vue$3.computedGetter [as default] (eval at <anonymous> (http://localhost:3000/app.js:600:2), <anonymous>:1967:15)
>at Object.get [as default] (eval at <anonymous> (http://localhost:3000/app.js:654:2), <anonymous>:519:42)
>at _merge (eval at <anonymous> (http://localhost:3000/app.js:978:2), <anonymous>:413:42)
>at _merge (eval at <anonymous> (http://localhost:3000/app.js:978:2), <anonymous>:420:13)
> at _merge (eval at <anonymous> (http://localhost:3000/app.js:978:2), <anonymous>:420:13)
>at _merge (eval at <anonymous> (http://localhost:3000/app.js:978:2), <anonymous>:420:13)
>error @ vue-resource.common.js?2f13:280

That's my code : 

News.vue : (in the <script></script> part)
```<script>
import { mapGetters, mapActions } from 'vuex'

export default {
    name: 'news',
    data() {
        return {}
    },
    computed: mapGetters({
        allnews: 'allnews'
    }),
    methods: mapActions({
        loadAllNews: 'loadAllNews',
        publish:     'publish',
        unpublish:   'unpublish'
    }),
    mounted() {
        this.loadAllNews()
    }
}
```

News.js : wich is my Store Module for News
```
import Api        from '../Api/Api.js'
import * as types from '../Mutations-Types.js'

const state = {
    news: [],
    current: {
        cursor: false,
        news:  false,
        error: false
    }
}
const getters = {
    allnews: state => state.news
}
const actions = {
    loadAllNews({ commit, state }) {
        if(state.news.length < 1) {
            Api.getNews().then((response) => {
                commit(types.LOAD_NEWS, response.data)
            }, (Error) => {
                console.error(Error)
            })
        }
    },
    getNewsBySlug({ commit, state }, slug) {
        let isExist;
        let current;
        for(let i in state.news) {
            if(state.news[i].slug == slug) {
                current = i;
                isExist = state.news[i];
            }
        }

        if(typeof isExist === 'undefined') {
            Api.getNewsBySlug(slug).then((response) => {
                commit(types.ADD_NEWS, response.data)
                commit(types.SELECT_NEWS, {  cursor: current, news: response.data, error: false })
            }, (Error) => {
                console.log(Error)
                commit(types.SELECT_NEWS, { cursor: current, news: false, error: Error })
            })
        } else {
            commit(types.SELECT_NEWS, { cursor: current, news: isExist, error: false })
        }
    },
    publish(slug) {
        Api.publishNews(slug).then((response) => {
            commit(types.PUBLISH_NEWS, slug)
        }, (Error) => {
            console.log(Error)
        })
    },
    unpublish(slug) {
        Api.unpublishNews(slug).then((response) => {
            commit(types.UNPUBLISH_NEWS, slug)
        }, (Error) => {
            console.log(Error)
        })
    }
}
const mutations = {
    [types.ADD_NEWS] (state, news) {
        if(!(news in state.news)) {
            state.news.push(news)
        }
    },
    [types.LOAD_NEWS] (state, news) {
        state.news = news
    },
    [types.SELECT_NEWS] (state, news) {
        state.current = news
    },
    [types.PUBLISH_NEWS] (state, slug) {
        for(let i in state.news) {
            if(state.news[i].slug == slug) {
                state.news[i].isPublic = true
            }
        }
    },
    [types.UNPUBLISH_NEWS] (state, slug) {
        for(let i in state.news) {
            if(state.news[i].slug == slug) {
                state.news[i].isPublic = false
            }
        }
    }
}

export default {
    state,
    getters,
    actions,
    mutations
}
```

Api.js : 

```
import {
    NewsResource,
    ThematiqueResource,
    PagesResource,
    AteliersResource,
    EventsResource,
    OutilsResource
} from './Resources.js'

export default {
    getNews: () => {
        return NewsResource.get()
    },
    getNewsBySlug: (slug) => {
        return NewsResource.get({ slug: slug })
    },
    publishNews: (slug) => {
        return NewsResource.publish({ slug: slug })
    },
    unpublishNews: (slug) => {
        return NewsResource.unpublish({ slug: slug })
    },
    getSlides: () => {
        return SlidesResource.get()
    },
    getThematiques: () => {
        return ThematiqueResource.get()
    },
    getPages: () => {
        return PagesResource.get()
    },
    getPagesByThematique: (thematique) => {
        return PagesResource.get({ thematique: thematique })
    },
    getAteliers: () => {
        return AteliersResource.get()
    },
    getEvents: () => {
        return EventsResource.get()
    },
    getOutils: () => {
        return OutilsResource.get()
    },
    getPartenaires: () => {
        return PartenaireResource.get()
    }
}
```
And finaly the Resource.js file : 
Note: in this file i already try to create personnal resources for /api/news/publish route, but i got the same...

```
import Vue          from 'vue'
import VueResource  from 'vue-resource'
import { API_ROOT } from './Config.js'

Vue.use(VueResource)

const customNews = {
    publish:   {method: 'PUT', url: API_ROOT + 'news/publish{/slug}'},
    unpublish: {method: 'PUT', url: API_ROOT + 'news/unpublish{/slug}'}
}

export const NewsResource       = Vue.resource(API_ROOT + 'news{/slug}{/limit}{/offset}', {}, customNews);
```

Don't understand what's is this error and where it came from, someone can help ?

Thx in advance

**Comment by CafaAsbl** [comment]
Ok, my bad, i found the solution.

In my mutations constant, in publish() and unpublish() function i forgot to set the { commit }.

Before : 
```
publish(slug) {
    [...]
}
```

After : 
```
publish({ commit }, slug) {
    [...]
}
```

I'm trying to place some words on that because i don't fully get it.
If i says : When i forgot to inject the { commit }, i forgot to inject the store, and so that's why VueJS can't set the getters ? Caus' it can't reach the store inside the function, 

Is that correct ? Or i'm out of understanding ?

Thx in advance :) 

ps: Sorry if my english is bad, english is not my natural language.
